# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import pulsar_pb2 as protos_dot_pulsar__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/pulsar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub(object):
    """Coordinator service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/minipulsar.CoordinatorService/Register',
                request_serializer=protos_dot_pulsar__pb2.RegisterRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/minipulsar.CoordinatorService/Heartbeat',
                request_serializer=protos_dot_pulsar__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.CreateTopic = channel.unary_unary(
                '/minipulsar.CoordinatorService/CreateTopic',
                request_serializer=protos_dot_pulsar__pb2.CreateTopicRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.CreateTopicResponse.FromString,
                _registered_method=True)
        self.SubscribeMessage = channel.unary_unary(
                '/minipulsar.CoordinatorService/SubscribeMessage',
                request_serializer=protos_dot_pulsar__pb2.SubscribeMessageRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.SubscribeMessageResponse.FromString,
                _registered_method=True)
        self.ListTopics = channel.unary_unary(
                '/minipulsar.CoordinatorService/ListTopics',
                request_serializer=protos_dot_pulsar__pb2.ListTopicsRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.ListTopicsResponse.FromString,
                _registered_method=True)
        self.GetRoutingTable = channel.unary_unary(
                '/minipulsar.CoordinatorService/GetRoutingTable',
                request_serializer=protos_dot_pulsar__pb2.GetRoutingTableRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.GetRoutingTableResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Coordinator service
    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutingTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=protos_dot_pulsar__pb2.RegisterRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=protos_dot_pulsar__pb2.HeartbeatRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.HeartbeatResponse.SerializeToString,
            ),
            'CreateTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTopic,
                    request_deserializer=protos_dot_pulsar__pb2.CreateTopicRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.CreateTopicResponse.SerializeToString,
            ),
            'SubscribeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeMessage,
                    request_deserializer=protos_dot_pulsar__pb2.SubscribeMessageRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.SubscribeMessageResponse.SerializeToString,
            ),
            'ListTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopics,
                    request_deserializer=protos_dot_pulsar__pb2.ListTopicsRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.ListTopicsResponse.SerializeToString,
            ),
            'GetRoutingTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutingTable,
                    request_deserializer=protos_dot_pulsar__pb2.GetRoutingTableRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.GetRoutingTableResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minipulsar.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minipulsar.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Coordinator service
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.CoordinatorService/Register',
            protos_dot_pulsar__pb2.RegisterRequest.SerializeToString,
            protos_dot_pulsar__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.CoordinatorService/Heartbeat',
            protos_dot_pulsar__pb2.HeartbeatRequest.SerializeToString,
            protos_dot_pulsar__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.CoordinatorService/CreateTopic',
            protos_dot_pulsar__pb2.CreateTopicRequest.SerializeToString,
            protos_dot_pulsar__pb2.CreateTopicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.CoordinatorService/SubscribeMessage',
            protos_dot_pulsar__pb2.SubscribeMessageRequest.SerializeToString,
            protos_dot_pulsar__pb2.SubscribeMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.CoordinatorService/ListTopics',
            protos_dot_pulsar__pb2.ListTopicsRequest.SerializeToString,
            protos_dot_pulsar__pb2.ListTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoutingTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.CoordinatorService/GetRoutingTable',
            protos_dot_pulsar__pb2.GetRoutingTableRequest.SerializeToString,
            protos_dot_pulsar__pb2.GetRoutingTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BrokerServiceStub(object):
    """Broker service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/minipulsar.BrokerService/Publish',
                request_serializer=protos_dot_pulsar__pb2.PublishRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.AssignPartition = channel.unary_unary(
                '/minipulsar.BrokerService/AssignPartition',
                request_serializer=protos_dot_pulsar__pb2.AssignPartitionRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.AssignPartitionResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/minipulsar.BrokerService/Subscribe',
                request_serializer=protos_dot_pulsar__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.SubscribeResponse.FromString,
                _registered_method=True)


class BrokerServiceServicer(object):
    """Broker service
    """

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignPartition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=protos_dot_pulsar__pb2.PublishRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.PublishResponse.SerializeToString,
            ),
            'AssignPartition': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignPartition,
                    request_deserializer=protos_dot_pulsar__pb2.AssignPartitionRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.AssignPartitionResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=protos_dot_pulsar__pb2.SubscribeRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.SubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minipulsar.BrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minipulsar.BrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrokerService(object):
    """Broker service
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.BrokerService/Publish',
            protos_dot_pulsar__pb2.PublishRequest.SerializeToString,
            protos_dot_pulsar__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignPartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.BrokerService/AssignPartition',
            protos_dot_pulsar__pb2.AssignPartitionRequest.SerializeToString,
            protos_dot_pulsar__pb2.AssignPartitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/minipulsar.BrokerService/Subscribe',
            protos_dot_pulsar__pb2.SubscribeRequest.SerializeToString,
            protos_dot_pulsar__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StorageServiceStub(object):
    """Storage service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/minipulsar.StorageService/Append',
                request_serializer=protos_dot_pulsar__pb2.AppendRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/minipulsar.StorageService/Read',
                request_serializer=protos_dot_pulsar__pb2.ReadRequest.SerializeToString,
                response_deserializer=protos_dot_pulsar__pb2.ReadResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Storage service
    """

    def Append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=protos_dot_pulsar__pb2.AppendRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.AppendResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=protos_dot_pulsar__pb2.ReadRequest.FromString,
                    response_serializer=protos_dot_pulsar__pb2.ReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minipulsar.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minipulsar.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Storage service
    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.StorageService/Append',
            protos_dot_pulsar__pb2.AppendRequest.SerializeToString,
            protos_dot_pulsar__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minipulsar.StorageService/Read',
            protos_dot_pulsar__pb2.ReadRequest.SerializeToString,
            protos_dot_pulsar__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
